### ISSUE TITLE
About creating the database and the tables

### ISSUE THREAD

**Issue by chkhu** [Aziily/BS_design_2023_autumn#1]
Is there a separate file like `create.sql` in this project? Or the job is done by `backend/database/models.py`? If so, how?

When I was trying to replicate this project on my local machine, I stumbled through running backend and frontend as instructed. When it comes to the mqtt server, it gave errors like 
```
pymysql.err.OperationalError: (1049, "Unknown database 'bs_iot_db'")
```
(bs_iot_db is the name i chose for the database, I have edited it accordingly in two config.yaml files)

I suppose it's because the database and the tables have not been created as expected (so, obviously the backend and frontend weren't functioning properly either). 

I wonder which part of this project is responsible for creating the database, so that I can work on it from that point.

**Comment by Aziily** [comment]
As mentioned in readme, this part is responsible for the creation of tables 
https://github.com/Aziily/BS_design_2023_autumn/blob/main/backend/database/__init__.py#L14, I am not sure whether you have created the database by yourself because the code is only responsible for creating tables and the database should exist first.

There is part of the code for the initialization of code.
```python
def Initialize():    
    db.drop_all()
    db.create_all()
    ...
```
As you can see, the code only creates tables owing to that I didn't find proper way for automatic creation of database. So, you should first create database by yourself in mysql CLI.

There is still one thing I should mention. As you are a ZJU student too, remember not to copy my code. Thanks for your issue.

**Comment by chkhu** [comment]
Thank you for your explanation. I think I grabbed what problem I ran into then.

> There is still one thing I should mention. As you are a ZJU student too, remember not to copy my code. Thanks for your issue.

Yes I am. No worries because I have decided to start over to build a vue project from scratch by my own. Thanks again for your inspiration.

**Comment by chkhu** [comment]
Thank you for your explanation. I think I grabbed what problem I ran into then.

> There is still one thing I should mention. As you are a ZJU student too, remember not to copy my code. Thanks for your issue.

Yes I am. No worries because I have decided to start over to build a vue project from scratch by my own. Thanks again for your inspiration.
